export interface BHPreset {
  name: string;
  shortName: string;
  category: 'stellar' | 'supermassive' | 'agn' | 'tde' | 'merger' | 'galactic';
  source: string;
  year: string;
  description: string;
  mass: number;
  spin: number;
  charge: number;
  distance: number;
  diskIntensity: number;
  exposure: number;
  frameDrag: number;
  darkMatter: number;
  modelType: number;
  aberration: number;
  coupling: number;
  rayMaxDepth: number;
  eddingtonRatio: number;
  diskViscosity: number;
  jetLorentzFactor: number;
  stellarDispersion: number;
  impactParameter: number;
  diskAspectRatio: number;
  massOutflowRate: number;
  agnFeedbackEff: number;
  massRatio: number;
  chirpMass: number;
  orbitalEcc: number;
  hotHaloTemp: number;
  darkMatterConc: number;
  mSigmaAlpha: number;
  realMassSolar: string;
  realDistanceLy: string;
}

export const RESEARCH_PRESETS: BHPreset[] = [
  {
    name: "Sagittarius A*",
    shortName: "Sgr A*",
    category: "supermassive",
    source: "EHT 2022 · GRAVITY 2019",
    year: "2022",
    description: "Milky Way galactic centre. Mass 4.154×10⁶ M☉ confirmed by S2 stellar orbit (GRAVITY). Spin parameter constrained by EHT imaging.",
    mass: 14.5,
    spin: 0.9,
    charge: 0.0,
    distance: 12.0,
    diskIntensity: 4.5,
    exposure: 1.8,
    frameDrag: 0.92,
    darkMatter: 0.6,
    modelType: 1,
    aberration: 0.0,
    coupling: 8.0,
    rayMaxDepth: 600,
    eddingtonRatio: 0.0001,
    diskViscosity: 0.12,
    jetLorentzFactor: 1.5,
    stellarDispersion: 103.0,
    impactParameter: 1.0,
    diskAspectRatio: 0.02,
    massOutflowRate: 0.05,
    agnFeedbackEff: 0.0,
    massRatio: 1.0,
    chirpMass: 0.0,
    orbitalEcc: 0.0,
    hotHaloTemp: 8e7,
    darkMatterConc: 18.0,
    mSigmaAlpha: 4.24,
    realMassSolar: "4.154 × 10⁶ M☉",
    realDistanceLy: "26,000 ly"
  },
  {
    name: "M87*",
    shortName: "M87*",
    category: "supermassive",
    source: "EHT 2019 · Event Horizon Telescope",
    year: "2019",
    description: "First black hole ever imaged. Mass 6.5×10⁹ M☉. Located in giant elliptical galaxy Messier 87. Powers a relativistic jet extending 5,000 ly.",
    mass: 22.0,
    spin: 0.94,
    charge: 0.0,
    distance: 18.0,
    diskIntensity: 8.0,
    exposure: 2.4,
    frameDrag: 0.94,
    darkMatter: 0.8,
    modelType: 1,
    aberration: 0.1,
    coupling: 12.0,
    rayMaxDepth: 800,
    eddingtonRatio: 0.001,
    diskViscosity: 0.08,
    jetLorentzFactor: 6.0,
    stellarDispersion: 324.0,
    impactParameter: 1.0,
    diskAspectRatio: 0.05,
    massOutflowRate: 0.15,
    agnFeedbackEff: 0.12,
    massRatio: 1.0,
    chirpMass: 0.0,
    orbitalEcc: 0.0,
    hotHaloTemp: 3e7,
    darkMatterConc: 8.0,
    mSigmaAlpha: 4.38,
    realMassSolar: "6.5 × 10⁹ M☉",
    realDistanceLy: "53.49 Mly"
  },
  {
    name: "Cygnus X-1",
    shortName: "CygX-1",
    category: "stellar",
    source: "Miller-Jones et al. 2021 · Science",
    year: "2021",
    description: "Canonical stellar-mass BH in X-ray binary. Mass 21.2 M☉, spin a* ≥ 0.9985. Located in Cygnus constellation. Sub-Eddington hard state.",
    mass: 1.8,
    spin: 0.998,
    charge: 0.0,
    distance: 3.5,
    diskIntensity: 12.0,
    exposure: 3.2,
    frameDrag: 0.999,
    darkMatter: 0.0,
    modelType: 1,
    aberration: 0.3,
    coupling: 6.0,
    rayMaxDepth: 300,
    eddingtonRatio: 0.02,
    diskViscosity: 0.25,
    jetLorentzFactor: 2.0,
    stellarDispersion: 0.0,
    impactParameter: 1.0,
    diskAspectRatio: 0.015,
    massOutflowRate: 0.08,
    agnFeedbackEff: 0.0,
    massRatio: 1.0,
    chirpMass: 0.0,
    orbitalEcc: 0.018,
    hotHaloTemp: 0.0,
    darkMatterConc: 0.0,
    mSigmaAlpha: 0.0,
    realMassSolar: "21.2 M☉",
    realDistanceLy: "7,240 ly"
  },
  {
    name: "GRS 1915+105",
    shortName: "GRS 1915",
    category: "stellar",
    source: "McClintock et al. 2006 · ApJ",
    year: "2006",
    description: "The fastest-spinning stellar black hole known. Spin a* ≈ 0.98–0.99. Mass 12.4 M☉. Produces superluminal jets, strong quasi-periodic oscillations.",
    mass: 1.4,
    spin: 0.98,
    charge: 0.0,
    distance: 4.0,
    diskIntensity: 15.0,
    exposure: 2.8,
    frameDrag: 0.98,
    darkMatter: 0.0,
    modelType: 1,
    aberration: 0.4,
    coupling: 14.0,
    rayMaxDepth: 350,
    eddingtonRatio: 1.2,
    diskViscosity: 0.3,
    jetLorentzFactor: 2.3,
    stellarDispersion: 0.0,
    impactParameter: 1.0,
    diskAspectRatio: 0.04,
    massOutflowRate: 0.2,
    agnFeedbackEff: 0.0,
    massRatio: 1.0,
    chirpMass: 0.0,
    orbitalEcc: 0.0,
    hotHaloTemp: 0.0,
    darkMatterConc: 0.0,
    mSigmaAlpha: 0.0,
    realMassSolar: "12.4 M☉",
    realDistanceLy: "36,000 ly"
  },
  {
    name: "AT2018dyb TDE",
    shortName: "TDE-dyb",
    category: "tde",
    source: "Leloudas et al. 2019 · A&A",
    year: "2019",
    description: "Tidal Disruption Event — solar-type star disrupted by a ~10⁷ M☉ BH. Super-Eddington phase at peak. Blue shifted outflow at ~0.1c detected by SIFTER.",
    mass: 12.0,
    spin: 0.6,
    charge: 0.0,
    distance: 10.0,
    diskIntensity: 18.0,
    exposure: 4.0,
    frameDrag: 0.6,
    darkMatter: 0.2,
    modelType: 1,
    aberration: 0.1,
    coupling: 10.0,
    rayMaxDepth: 400,
    eddingtonRatio: 12.0,
    diskViscosity: 0.15,
    jetLorentzFactor: 1.0,
    stellarDispersion: 80.0,
    impactParameter: 0.9,
    diskAspectRatio: 0.3,
    massOutflowRate: 0.45,
    agnFeedbackEff: 0.0,
    massRatio: 1.0,
    chirpMass: 0.0,
    orbitalEcc: 0.0,
    hotHaloTemp: 1e6,
    darkMatterConc: 12.0,
    mSigmaAlpha: 4.0,
    realMassSolar: "~10⁷ M☉",
    realDistanceLy: "370 Mly"
  },
  {
    name: "GW150914 Merger",
    shortName: "GW150914",
    category: "merger",
    source: "LIGO/Virgo 2015 · PRL 2016",
    year: "2016",
    description: "First gravitational wave detection. Two stellar BHs (36 M☉ + 29 M☉) merged into a 62 M☉ remnant. Peak strain h ≈ 10⁻²¹. Final spin ~0.67.",
    mass: 2.5,
    spin: 0.67,
    charge: 0.0,
    distance: 5.5,
    diskIntensity: 2.0,
    exposure: 2.0,
    frameDrag: 0.67,
    darkMatter: 0.0,
    modelType: 0,
    aberration: 0.0,
    coupling: 5.0,
    rayMaxDepth: 250,
    eddingtonRatio: 0.0,
    diskViscosity: 0.1,
    jetLorentzFactor: 1.0,
    stellarDispersion: 0.0,
    impactParameter: 1.0,
    diskAspectRatio: 0.0,
    massOutflowRate: 0.0,
    agnFeedbackEff: 0.0,
    massRatio: 0.81,
    chirpMass: 28.3,
    orbitalEcc: 0.0,
    hotHaloTemp: 0.0,
    darkMatterConc: 0.0,
    mSigmaAlpha: 0.0,
    realMassSolar: "62 M☉ remnant",
    realDistanceLy: "1.4 Gly"
  },
  {
    name: "NGC 4889 BCG",
    shortName: "NGC4889",
    category: "supermassive",
    source: "McConnell et al. 2011 · Nature",
    year: "2011",
    description: "Brightest cluster galaxy in Coma Cluster. Hosts one of the most massive BHs known: 21×10⁹ M☉. Strong M-σ correlation anchor. σ ≈ 347 km/s.",
    mass: 24.0,
    spin: 0.5,
    charge: 0.0,
    distance: 22.0,
    diskIntensity: 3.0,
    exposure: 1.5,
    frameDrag: 0.5,
    darkMatter: 1.5,
    modelType: 0,
    aberration: 0.0,
    coupling: 8.0,
    rayMaxDepth: 700,
    eddingtonRatio: 0.00005,
    diskViscosity: 0.05,
    jetLorentzFactor: 1.0,
    stellarDispersion: 347.0,
    impactParameter: 1.0,
    diskAspectRatio: 0.01,
    massOutflowRate: 0.0,
    agnFeedbackEff: 0.0,
    massRatio: 1.0,
    chirpMass: 0.0,
    orbitalEcc: 0.0,
    hotHaloTemp: 5e7,
    darkMatterConc: 5.0,
    mSigmaAlpha: 4.24,
    realMassSolar: "2.1 × 10¹⁰ M☉",
    realDistanceLy: "336 Mly"
  },
  {
    name: "Sgr A* S2 Orbit",
    shortName: "S2 Orbit",
    category: "galactic",
    source: "GRAVITY Collab. 2018 · A&A · Keck/UCLA",
    year: "2018",
    description: "Star S2 orbiting Sgr A* — closest periapsis passage 2018. Orbital period 16.0 yr, eccentricity e=0.8843. Schwarzschild precession directly measured.",
    mass: 14.5,
    spin: 0.9,
    charge: 0.0,
    distance: 8.0,
    diskIntensity: 2.0,
    exposure: 2.0,
    frameDrag: 0.9,
    darkMatter: 0.5,
    modelType: 1,
    aberration: 0.1,
    coupling: 6.0,
    rayMaxDepth: 500,
    eddingtonRatio: 0.0001,
    diskViscosity: 0.1,
    jetLorentzFactor: 1.0,
    stellarDispersion: 103.0,
    impactParameter: 0.8843,
    diskAspectRatio: 0.02,
    massOutflowRate: 0.02,
    agnFeedbackEff: 0.0,
    massRatio: 1.0,
    chirpMass: 0.0,
    orbitalEcc: 0.8843,
    hotHaloTemp: 8e7,
    darkMatterConc: 18.0,
    mSigmaAlpha: 4.24,
    realMassSolar: "4.154 × 10⁶ M☉",
    realDistanceLy: "26,000 ly"
  },
  {
    name: "TON 618 Quasar",
    shortName: "TON 618",
    category: "supermassive",
    source: "Shemmer et al. 2004 · ApJ",
    year: "2004",
    description: "Ultra-massive quasar BH, one of the most massive known. Mass 6.6×10¹⁰ M☉. Hyper-luminous AGN at z=2.219. Extreme accretion power.",
    mass: 25.0,
    spin: 0.7,
    charge: 0.0,
    distance: 25.0,
    diskIntensity: 20.0,
    exposure: 3.5,
    frameDrag: 0.7,
    darkMatter: 2.0,
    modelType: 1,
    aberration: 0.2,
    coupling: 20.0,
    rayMaxDepth: 900,
    eddingtonRatio: 2.0,
    diskViscosity: 0.1,
    jetLorentzFactor: 8.0,
    stellarDispersion: 400.0,
    impactParameter: 1.0,
    diskAspectRatio: 0.1,
    massOutflowRate: 0.3,
    agnFeedbackEff: 0.25,
    massRatio: 1.0,
    chirpMass: 0.0,
    orbitalEcc: 0.0,
    hotHaloTemp: 2e8,
    darkMatterConc: 4.0,
    mSigmaAlpha: 4.5,
    realMassSolar: "6.6 × 10¹⁰ M☉",
    realDistanceLy: "10.37 Gly"
  },
  {
    name: "Cool-Gas Quenching Track",
    shortName: "CoolGas-Q",
    category: "agn",
    source: "Nature 2024 · Black holes regulate cool-gas accretion",
    year: "2024",
    description: "Massive-galaxy AGN feedback pathway where black-hole growth suppresses cool-gas fraction and drives quiescence. Tuned for high-pressure halo + moderate jet coupling.",
    mass: 19.5,
    spin: 0.82,
    charge: 0.0,
    distance: 16.0,
    diskIntensity: 6.0,
    exposure: 2.1,
    frameDrag: 0.82,
    darkMatter: 1.2,
    modelType: 1,
    aberration: 0.08,
    coupling: 18.0,
    rayMaxDepth: 1100,
    eddingtonRatio: 0.004,
    diskViscosity: 0.09,
    jetLorentzFactor: 4.5,
    stellarDispersion: 290.0,
    impactParameter: 1.0,
    diskAspectRatio: 0.025,
    massOutflowRate: 0.18,
    agnFeedbackEff: 0.2,
    massRatio: 1.0,
    chirpMass: 0.0,
    orbitalEcc: 0.0,
    hotHaloTemp: 9e7,
    darkMatterConc: 6.0,
    mSigmaAlpha: 4.3,
    realMassSolar: "~10⁹ M☉",
    realDistanceLy: "~1 Gly"
  },
  {
    name: "S0-2 Relativistic Orbit",
    shortName: "S0-2",
    category: "galactic",
    source: "Keck/UCLA + GRAVITY 2018–2024",
    year: "2024",
    description: "High-eccentricity stellar orbits near Sgr A* including periapse precession and strong-field overlap structure for 3D/4D orbit diagnostics.",
    mass: 14.5,
    spin: 0.92,
    charge: 0.0,
    distance: 7.5,
    diskIntensity: 2.8,
    exposure: 2.3,
    frameDrag: 0.9,
    darkMatter: 0.55,
    modelType: 1,
    aberration: 0.12,
    coupling: 11.0,
    rayMaxDepth: 1050,
    eddingtonRatio: 0.0002,
    diskViscosity: 0.1,
    jetLorentzFactor: 1.0,
    stellarDispersion: 103.0,
    impactParameter: 0.89,
    diskAspectRatio: 0.02,
    massOutflowRate: 0.01,
    agnFeedbackEff: 0.0,
    massRatio: 1.0,
    chirpMass: 0.0,
    orbitalEcc: 0.89,
    hotHaloTemp: 8e7,
    darkMatterConc: 18.0,
    mSigmaAlpha: 4.24,
    realMassSolar: "4.154 × 10⁶ M☉",
    realDistanceLy: "26,000 ly"
  },
  {
    name: "Radio AGN Jet",
    shortName: "Radio AGN",
    category: "agn",
    source: "Fabian 2012 · ARA&A · McNamara & Nulsen 2007",
    year: "2012",
    description: "Radio-mode AGN feedback. Mechanically powerful jets inflate X-ray cavities in hot gas halos, preventing runaway cooling. Represents passive galaxy regulatory cycle.",
    mass: 18.0,
    spin: 0.85,
    charge: 0.0,
    distance: 15.0,
    diskIntensity: 5.0,
    exposure: 1.8,
    frameDrag: 0.85,
    darkMatter: 1.0,
    modelType: 1,
    aberration: 0.05,
    coupling: 15.0,
    rayMaxDepth: 600,
    eddingtonRatio: 0.003,
    diskViscosity: 0.06,
    jetLorentzFactor: 5.0,
    stellarDispersion: 250.0,
    impactParameter: 1.0,
    diskAspectRatio: 0.03,
    massOutflowRate: 0.12,
    agnFeedbackEff: 0.18,
    massRatio: 1.0,
    chirpMass: 0.0,
    orbitalEcc: 0.0,
    hotHaloTemp: 6e7,
    darkMatterConc: 7.0,
    mSigmaAlpha: 4.4,
    realMassSolar: "~10⁹ M☉",
    realDistanceLy: "~500 Mly"
  }
];

export const CATEGORY_COLORS: Record<string, string> = {
  stellar: '#f97316',
  supermassive: '#a78bfa',
  agn: '#06b6d4',
  tde: '#10b981',
  merger: '#f43f5e',
  galactic: '#fbbf24'
};

export const CATEGORY_LABELS: Record<string, string> = {
  stellar: 'Stellar BH',
  supermassive: 'Supermassive',
  agn: 'AGN',
  tde: 'TDE',
  merger: 'Binary Merger',
  galactic: 'Galactic Centre'
};
